### ISSUE TITLE
Trying to get Line@ to send messages only to group chats. Humbly requesting some help.

### ISSUE THREAD

**Issue by collektor** [line/line-platform-feedback#10]
Hi, I am a newbie with GIT and LINE API. 

How do I get my Line@ account to send message to only groups that my account is in? Currently using Line@ manager only allows me to compose and send message to all individual friends.

Thank you!

**Comment by GuitarSucks** [comment]
Hi, @collektor 
This is a bot related faq. Your question seems to be more related to LINE@ account itself and not about a bot. 
I recommend that you visit the LINE@ faq which is [here](https://help2.line.me/line_at_application/android/pc?lang=en) .
