### ISSUE TITLE
Can't re-code the bot

### ISSUE THREAD

**Issue by Sriend** [line/line-platform-feedback#103]
Sorry if i post it at wrong place.

I have tried the guide from [Message API Developers LINE](https://developers.line.me/en/docs/messaging-api/building-bot/) Where my result of the bot that it only can reply what i typed.

is there any guide for me to edited the code or reference and example? i have tried looked arround and still can't find it (youtube, github, google, line, etc)

If anyone can share and teach please gimme reply at here or direct to my Mail (Happy.sriend@gmail.com)

Thanks for the time and read my post and also sorry for trouble.

**Comment by tokuhirom** [comment]
There's SDK for messaging APIs.
For example, there's Java SDK. https://github.com/line/line-bot-sdk-java
Every SDK contains example code. You can read it.

For example, you can deploy the Java version of echo bot on Heroku by the Heroku button.
https://github.com/line/line-bot-sdk-java/tree/master/sample-spring-boot-echo
