### ISSUE TITLE
Track LIFF consent screen

### ISSUE THREAD

**Issue by dlackty** [line/line-platform-feedback#106]
So when users tap on LIFF link first time, it will show a consent screen to users like below:
![png](https://user-images.githubusercontent.com/14349/42490348-4bf95532-8442-11e8-9579-ff9a78466026.png)

However, if users decline to authorize on this screen, he/she will be brought back to chat screen.

How do we:
1. Provide a fallback?
2. Track number of users that decline to authorize?

**Comment by tori3** [comment]
Hi @dlackty 
There is currently no way to track like that.
Thanks for your feedback.
