### ISSUE TITLE
LIFF App URL can not open with Android device.

### ISSUE THREAD

**Issue by morugu** [line/line-platform-feedback#107]
![liff-error](https://user-images.githubusercontent.com/1635118/42611390-d594c2c4-85d0-11e8-8e20-dfc2b1a205bd.jpg)

I checked the error with the following procedure.  

- The URL of already created LIFF application can be opened without a problem.
- In LINE App > Account> Deauthorize from linked application, URL can not be opened.
- I created a new channel and set the URL of the LIFF application, but I could not open the URL. line://app/1593543749-zpbK1oGM

and I found other reports.
https://linedevelopers.slack.com/archives/C8BEERVGX/p1531312013000193
https://twitter.com/gottote_ru/status/1017069904539729920?s=09

I think that it is an error when opening the initial authentication screen.

device 1
Android 8.1.0
LINE 8.10.1

device 2
Android 7.1.1
LINE 8.10.1

**Comment by tori3** [comment]
Hi @morugu 

Issue on our server side and it happen on LINE Android v8.10.1. already it has been fixed.
thanks for your report and sorry for inconvenience.

Regards
