### ISSUE TITLE
LINEapp for iOS does not work action attribute on FlexMessage

### ISSUE THREAD

**Issue by satoutetsuya** [line/line-platform-feedback#117]
My chatbot sends FlexMessage of Messaging API, which includes Buttons with actions attribute. 

LINEapp for Android works correctly that sends message to bot.
But LINE for iOS does not work. It shows dialog "ご利用のバージョンでは対応していません。LINEアプリを最新バージョンにアップデートしてください。" and does not send message.

Message json object which my bot sends below.
`
[{"type": "flex", "altText": "確認", "contents": {"type": "bubble", "direction": "ltr", "body": {"type": "box", "layout": "vertical", "spacing": "none", "margin": "none", "contents": [{"type": "text", "text": "確認", "wrap": true, "weight": "bold"}, {"type": "text", "text": "以下のキーワードに当てはまりますか？\n「締結」\n（現在の候補 10件）", "margin": "none", "size": "sm", "wrap": true}, {"type": "separator", "margin": "xs"}, {"type": "separator", "margin": "xs"}, {"type": "text", "text": "[1] はい", "margin": "sm", "wrap": true, "color": "#0000ff", "action": {"type": "message", "text": 1}}, {"type": "separator", "margin": "xs"}, {"type": "text", "text": "[2] いいえ", "margin": "sm", "wrap": true, "color": "#0000ff", "action": {"type": "message", "text": 2}}, {"type": "separator", "margin": "xs"}, {"type": "text", "text": "[3] わかりません", "margin": "sm", "wrap": true, "color": "#0000ff", "action": {"type": "message", "text": 3}}, {"type": "separator", "margin": "xs"}, {"type": "text", "text": "[4] 質問一覧を見る", "margin": "sm", "wrap": true, "color": "#0000ff", "action": {"type": "message", "text": 4}}, {"type": "separator", "margin": "xs"}, {"type": "text", "text": "[0] 最初に戻る", "margin": "sm", "wrap": true, "color": "#0000ff", "action": {"type": "message", "text": 0}}]}}}]
`

Please help me to work on iOS.

**Comment by satoutetsuya** [comment]
It depends on type of action.

URIAction works fine.
But MessageAction and PostbackAction does not work.

**Comment by synk** [comment]
`text` property should be a text (e.g. `"0"`), not number.
by the way, which version of LINE iOS app do you use?

**Comment by satoutetsuya** [comment]
@synk 
Thank you for your comment. I wil try to send text property as string.

LINE app version is 8.13.0.
I tested on  iPhone5S,(iOS11.4) and iPhone7(iOS10.3).

**Comment by satoutetsuya** [comment]
@synk 
It works fine when send text as String.
Thank you for your help.
