### ISSUE TITLE
No 'Bot Settings' menu

### ISSUE THREAD

**Issue by rern** [line/line-platform-feedback#14]
My account in **Line Business Center** has
1.  **Line@** Developer with 
     **Line@ Manager** and **Line Developers** buttons
     **Line@ ID** (random)
     **Bot Settings** menu
2.  **Line@** Free with 
     **Line@ Manager** buttons
      **Line@ Premium ID**
     **NO - Bot Settings** menu

How can I get **Bot Settings** menu for number 2 ?

Thanks

**Comment by GuitarSucks** [comment]
@rern 
You'll need to go to [Business Center](https://business.line.me) and select the LINE@ and go to details, then you will see a button to activate the API.
See our documentation for more details.
https://developers.line.me/messaging-api/getting-started#apply_messagingapi
