### ISSUE TITLE
Can not receive follow or join event from webhook url when line bot is add as a frind at first time

### ISSUE THREAD

**Issue by rst-geruliang** [line/line-platform-feedback#16]
Hi,everyone
When a line user add my line bot as a friend at first time, my server can not receive the follow event from webhookURL.
But, if this user block my line bot and unblock the line bot, my server then can receive the follow event.
And then even this user delete my line bot and add it again,  my server also can receive the follow event.
So I think my WebhookURL's setting is correct, but I don't understand why my server can not receive the event at firest time.
Can anyone help me to fix this problem?
Thank you very much

**Comment by GuitarSucks** [comment]
Hi, @rst-geruliang 

We haven't has such incident report and wasn't able to reproduce this. 
Is this problem still present ?

**Comment by rst-geruliang** [comment]
Hi, @GuitarSucks 

Thank you for answer my question.
I tried it again and this problem did not happen.
So please close this issus.

Thank you

**Comment by GuitarSucks** [comment]
@rst-geruliang 
Glad to hear the issue is not present :)
