### ISSUE TITLE
Is there any kick api for bot ?

### ISSUE THREAD

**Issue by oatto** [line/line-platform-feedback#17]
Hi,

I want to use line bot to kick people in the group, to protect nukers inviting other people to the group.

Thank you in advance.

**Comment by kumai** [comment]
Hi,

There's no API to kick out user from group.

**Comment by oatto** [comment]
@kumai
Thank you for your fast response.

I saw sirichan-bot is bot for kicking user.
Is it a fake bot ?
And if it really can kick users, how do they implement it ?

Thank you.
