### ISSUE TITLE
Allow bots to receive files

### ISSUE THREAD

**Issue by Fryyyyy** [line/line-platform-feedback#2]
Hi

It seems Line Bots can only receive pictures, not regular files as attachments? Are there plans to support this?

Thanks.

**Comment by GuitarSucks** [comment]
Not at this moment.
What type of attachments are you thinking of ?

**Comment by Fryyyyy** [comment]
Text files are enough for my application, but really I don't see why any file couldn't be sent, if you already allow it person -> person

**Comment by GuitarSucks** [comment]
@Fryyyyy 
Thanks for your comment. We will look into it if we can provide it in the future.
Regards

**Comment by Fryyyyy** [comment]
Ok, thank you.

Do you have a public development roadmap, or bug tracking interface to see the progress of the feature request?

Or a way of being notified when it is deployed?

I can't offer the service to my users until it's implemented.

Cheers!

**Comment by GuitarSucks** [comment]
Ill see what I can do about publishing our development roadmap.

**Comment by Fryyyyy** [comment]
Awesome :) Thanks so much

**Comment by Fryyyyy** [comment]
Bump :)

**Comment by Fryyyyy** [comment]
Bump

**Comment by GuitarSucks** [comment]
Hi
We already have a prototype for announcing our roadmap. Unfortunately we need to go through several review process to release it, which is taking some time.

Regards
