### ISSUE TITLE
Usable PUSH_MESSAGE API

### ISSUE THREAD

**Issue by mstephen77** [line/line-platform-feedback#20]
Hello,
I'm interested in Messaging API, and according to https://business.line.me/en/services/bot the messaging API is should have both REPLY_MESSAGE and PUSH_MESSAGE API for free.
But after creating a LINE@ account with Bot Settings enabled, it seems I could only use REPLY_MESSAGE. 

My question is, does PUSH_MESSAGE API available only for paid plans? If so, why https://business.line.me/en/services/bot said that it's available for free? (I apologize if I sounded rude, but I didn't mean to be rude).

Regards,
Michael Stephen.

**Comment by GuitarSucks** [comment]
For related questions,
Please notice that the pricing and plans are different per region.
Go to "http://at.line.me/" and select the region you are for more details.
