### ISSUE TITLE
How to turn on messageAPI bot in Line@ premium id

### ISSUE THREAD

**Issue by godoakbrutal** [line/line-platform-feedback#23]
I was create a **Line@ premium id** and I want to use Message API Bot with my account (Line@)
So when I try to use MessageAPI from Line Business Center and nothing happen.

Is possible that Line@ premium id will use Message API ? and how ?

Thank you for advance.

**Comment by mstephen77** [comment]
First of all, visit https://business.line.me/en/services/bot, scroll to the bottom and look for `"Click here to use Messaging API with an existing LINE@ account"`. Beware that you won't be able to use LINE@ app on that account once you did it. Also make sure you have enabled Bot Settings on the LINE@ Manager.

**Comment by godoakbrutal** [comment]
@mstephen77
Ok I've already click on `"Click here to use Messaging API with an existing LINE@ account"`
Then the page only show `"Start using Developer Trial"`.  like this image

<img width="628" alt="screen shot 2560-08-28 at 11 45 41 am" src="https://user-images.githubusercontent.com/10972026/29759487-7711ba3e-8be6-11e7-99f3-d5291d74bf2c.png">

My location to use is **Thailand**

Do you have any idea what I must do next.

**Comment by mstephen77** [comment]
@godoakbrutal 
Weird, after you click on `"Click here to use Messaging API with an existing LINE@ account"`, you should be brought to the screen where it asks you which existing LINE@ account to enable it on. Make sure you're logged in and you have an active LINE@ account.

Preview: 
![ss](https://user-images.githubusercontent.com/22470683/29759921-f41a8d00-8be9-11e7-987c-92518a61d811.jpg)

**Comment by godoakbrutal** [comment]
Ah I see but still have a problem.
Because I don't want to use a developer version. I want to use public version and I don't know how to use this. Do you have a way to do this ?

**Comment by mstephen77** [comment]
I don't know if that's available for you/your country. It should be possible to fake your location/country tho.

**Comment by GuitarSucks** [comment]
@mstephen77 
Sorry I deleted your comment. But it was inappropriate in our faq.

@godoakbrutal 
As @mstephen77 explained when you go to Business Center and click your LINE@ Account, you should be able to see the following.

![image](https://user-images.githubusercontent.com/3488533/29768308-b9fa3490-8c20-11e7-8e02-b2a93035e1ea.png)

If you don't see this option, is not available in your location.

**Comment by godoakbrutal** [comment]
@GuitarSucks 
Ah it's ok anyway thanks a lot @mstephen77 and @GuitarSucks

**Comment by benjaminfauchald** [comment]
@godoakbrutal But you are in Thailand?

![screenshot 2017-12-21 16 39 05_preview](https://user-images.githubusercontent.com/8008370/34249812-9acfb688-e66d-11e7-8572-42b4857498bf.png)


AFAIK This saids Thailand. We are using the messenger API here, how can not this connect to the API?

**Comment by godoakbrutal** [comment]
@benjaminfauchald But they don't have fully API such as `PUSH_MESSAGES` and don't have any price plan about `Messages API` they only have trial version if you want to use.

this is what I've found.
![screen shot 2560-12-25 at 10 07 44 am](https://user-images.githubusercontent.com/10972026/34331677-88f1b466-e95b-11e7-9b5d-034d38d13a6b.png)

But if you have an information can you send me a link ?
Thanks.
