### ISSUE TITLE
Usable APIs not support anything ?

### ISSUE THREAD

**Issue by godoakbrutal** [line/line-platform-feedback#24]
Hi. A few minutes ago I was created a **line @ account standard account** And then I try to `enable Bot API` in **LINE@Manager** and Usable APIs section not show anything . . .

#### **My location:** Thailand

**like this image**
![screen shot 2560-08-29 at 4 13 02 pm](https://user-images.githubusercontent.com/10972026/29813669-f7acebb6-8cd4-11e7-822c-c2773e2dfdce.png)

What is happening to my account. Is anyone can explain this to me.

Thanks for advance.

**Comment by tpkk0873** [comment]
Is the problem solved? I have just found the same symptom and would like to know how to figure it out.

**Comment by godoakbrutal** [comment]
@tpkk0873 
**How to solve ?**
You must register a new `line@ channel` and following the step
1. register channel https://developers.line.me/en/docs/messaging-api/getting-started/
2. on your `line@ channel` page you will see button name `Messageing API` and follow the step until finish

**ps.** in Thailand you can use only `trial version` for all `Usable APIs`. But if you want to use full version you must register line account as other country that support `Messaging APIs`

**Comment by tpkk0873** [comment]
Thank you very much for your answer.

Anyway, do you have any idea what does the country currently support? and how to register to LINE account on other country from Thailand. 

Thank you in advance for suggestion

**Comment by godoakbrutal** [comment]
@tpkk0873 
Haha sorry, I'm not sure  which country supported this function. :sweat_smile:

**Comment by tpkk0873** [comment]
thank you very much for your advise
