### ISSUE TITLE
Update FAQ about LINE Beacon

### ISSUE THREAD

**Issue by tokuhirom** [line/line-platform-feedback#25]
# LINE Beacon in `((( beacon shop )))` was sold out.
https://github.com/line/line-bot-faq/blob/master/README.md#how-do-i-get-a-line-beacon

Do you have plans to resume selling?
https://beacon.theshop.jp/items/4699062

If we don't have any plan, we need to remove the link.

# Can you add a link for line-simple-beacon repository?
https://github.com/line/line-simple-beacon

Users can create line beacon by themselves on LINE Simple Beacon spec.
We need to notice about line simple beacon.

**Comment by tokuhirom** [comment]
@yohsuke @GuitarSucks 
↑↑

**Comment by yohsuke** [comment]
> Do you have plans to resume selling?
> https://beacon.theshop.jp/items/4699062

I created the update pr. #26 

I'll also add simple beacon spec description.

**Comment by GuitarSucks** [comment]
#26 Merged
