### ISSUE TITLE
"Share" API?

### ISSUE THREAD

**Issue by wiradikusuma** [line/line-platform-feedback#3]
Is there any way for users to share (viral mechanism) my LINE@ account/bot? And preferably, a way to track it, so I can say, "Thanks for spreading the words, here's 500 virtual coins."

If such mechanism does not exist in LINE@, how do people usually do it?

**Comment by GuitarSucks** [comment]
There are few ways to share bot account 

1. Users can go to the "+" menu on a chat room and select the bot account from the friendlist to share on the room
2. Use url scheme to share "https://line.me/R/ti/p/{YOUR_BOT_ACCOUNT_ID}". You can find your link from "https://admin-official.line.me" -> Select your account -> Account Information.
3. Users can also share the above link on Timeline
4. You can try social plugin. see "https://media.line.me/en/#addfriend"

Although we don't have any tool to track it.
