### ISSUE TITLE
400 err code from the simple doc request

### ISSUE THREAD

**Issue by codenoid** [line/line-platform-feedback#32]
`The property, 'to', in the request body is invalid (line: -, column: -)`

scritp : 

```
import requests

headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer {xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}',
}

data = '{"to": "kutemukan","messages":[{"type":"text","text":"Hello, world1"},{"type":"text","text":"Hello, world2"}]}'

a = requests.post('https://api.line.me/v2/bot/message/push', headers=headers, data=data)
print(a.text)
```

**Comment by tokuhirom** [comment]
You need to put `ID of the receiver` for the 'to' property.  `ID of the receiver` is not a user readable ID. It looks like `U206d25c2ea6bd87c17655609a1c37cb8`, `Ca56f94637cc4347f90a25382909b24b9` or `Ra8dbf4673c4c812cd491258042226c99`.
You can get it from a webhook message.

ref. https://developers.line.me/en/docs/messaging-api/reference/#common-fields .

**Comment by codenoid** [comment]
yes, it has been fixed @tokuhirom , i get user ID from webhook,
