### ISSUE TITLE
Getting Username

### ISSUE THREAD

**Issue by mrsic** [line/line-platform-feedback#34]
Hi People When sombody write a message i get this on webhook

`(
    [events] => Array
        (
            [0] => Array
                (
                    [type] => message
                    [replyToken] => 93bf240f67a04aecb62d34fd43448686
                    [source] => Array
                        (
                            [groupId] => C057232b43f21acf60a710b8bf5daf410
                            [userId] => Uc9b327e1717abb22b280a49400f71rta
                            [type] => group
                        )

                    [timestamp] => 1510055327776
                    [message] => Array
                        (
                            [type] => text
                            [id] => 6954539977701
                            [text] => So ist not easy
                        )

                )

        )

)`

How i can get username of [userId] => Uc9b327e1717abb22b280a49400f71rta like @username without getting user profile

THIS MY PHP CODE

`if(strpos($message,"you are creazy")!==false){

$strings = array(
    ' /@username/ Please not insult my inteligence!',
    '/@username/  Tell that again and i will burn you!',
    '/@username/  You are not match smart!',
    '/@username/  You are just drunked!',
    '/@username/ How dare you!',
);
$key = array_rand($strings);
	$textMessageBuilder = new \LINE\LINEBot\MessageBuilder\TextMessageBuilder($strings[$key] );
$response = $bot->replyMessage($action['events']['0']['replyToken'], $textMessageBuilder);
if ($response->isSucceeded()) {
    require_once('../db_write.php');
    return;
}}
`

And other question if i use Line Login api i get same user Id  [userId] => Uc9b327e1717abb22b280a49400f71rta 
Thank You

**Comment by GuitarSucks** [comment]
@mrsic 
You can use the following API
https://developers.line.me/en/docs/messaging-api/reference/#get-profile
