### ISSUE TITLE
Sending text messages to user with LINE URL scheme?

### ISSUE THREAD

**Issue by RoyYouRoyYou** [line/line-platform-feedback#49]
Hi !  I've found that use LINE URL scheme can Sending text messages to bot by **bot_id** . 

So is there a way to send text message by using user's **line id** with LINE URL scheme ? (e.g. line://oaMessage/**{user's LINE_id}**/?{text_message} )

**Comment by kazuki-ma** [comment]
Sorry there is no way to do such thing with specific user.

But `line://msg/text/msg_text` is the scheme to send `msg_text` to specific user selected.
User who tap the URL should choose the receiver of this message.
