### ISSUE TITLE
Manage "friends" on Developer Trial plan (without line@app)

### ISSUE THREAD

**Issue by R-N** [line/line-platform-feedback#5]
So, after changing to developer trial plan, I can no longer use line@app with it, nor can I use 1-on-1 chat. That I agreed to. However is there really no way to manage "friends"? My bot just reached 50 friends limit. God knows who most of them are. Well, I cant find way to increase it on google. Just searching anything about line is already hard because of its name. Anyway, I want to at least be able to "block" some of its "friends" so I can test it with people I know. (about 15 people, not much). Or does it have to be the user who blocks my bot?

**Comment by krrrr38** [comment]
There is no way to add trial bot friends limitation. Trial bot is just for development and so on. So [if you want to add more friends, please create new one.](https://github.com/line/line-bot-faq#can-i-change-my-account-to-the-developer-trial-plan)

**Comment by R-N** [comment]
Theres no way to increase it and theres no way to remove friends either?

**Comment by kumai** [comment]
Yes, you cannot do either of those with a trial account.

**Comment by R-N** [comment]
Alright, Thanks for the answers. I could barely find anything about this on google. All I found was an old article about increasing friend limit to 5000 by requesting it to Line. The link in it was dead too.

**Comment by AlexanderGracetantiono** [comment]
idk if it will help,but for me  first make an line@, just line @ dont agree with trial development, and you can get free account, and then you can make bot from there
