### ISSUE TITLE
My Line official account cannot use push message api

### ISSUE THREAD

**Issue by puriphanr** [line/line-platform-feedback#50]
I already have an official account and develop application to push message to user , but it throw error message {"message":"Access to this API is not available for your account"}.
According to your API document, I think my account does not have permission to push message, but I can't found the button to add more permission, please recommend me . Many thanks

**My current permission**
![4-1-2561 21-22-15](https://user-images.githubusercontent.com/35105143/34567615-7c608672-f195-11e7-9fac-da0b6f66cbc0.jpg)

**Comment by kazuki-ma** [comment]
Looks like you should be able to access messaging API.

To identify your problem, could you contact us via LINE Partner or account manager (sales / tech support)?
Thank you.

**Comment by puriphanr** [comment]
Thank you for your help, it because my channel is using version 1 , I'll update my version.
