### ISSUE TITLE
Is there a way to check total ID in group chat

### ISSUE THREAD

**Issue by gokusenz** [line/line-platform-feedback#51]
I want to know total ID in group chat.

Is this possible? I haven't found a solution in the docs.

**Comment by kazuki-ma** [comment]
It's possible but only available for LINE@ Approved accounts or official accounts now.

https://developers.line.me/en/docs/messaging-api/group-chats/#getting-user-ids-of-the-members-of-a-group-or-room

> # Getting user IDs of the members of a group or room
> 
> Get the user IDs of the members of a group or a room where your bot has been added with the /group/{groupId}/members/ids and /room/{roomId}/members/ids endpoints. This retrieves user IDs of users who have not added the bot as a friend or has blocked the bot.
> 
> Note: This feature is only available for LINE@ Approved accounts or official accounts.
