### ISSUE TITLE
LINE BOTに連絡先を送信した場合の動作について

### ISSUE THREAD

**Issue by gazf** [line/line-platform-feedback#54]
MessagingAPIを使いBOTを作成しているところなのですが、BOTと1:1の状態で連絡先を送信してもMessagingAPIからのWebhookが送信されません。

以前のBOT APIでは実装されていたような記述が確認できましたが、MessagingAPIでは利用することができないのでしょうか？

[https://qiita.com/hiro_hosono/items/a744c420fd48c9e045ad](https://qiita.com/hiro_hosono/items/a744c420fd48c9e045ad)

ご返信いただければ幸いです。

**Comment by kazuki-ma** [comment]
現行バージョンの Messaging API では、連絡先（contact）タイプの Webhook は送信していません。

現状のご連絡のみとなりますが、よろしくお願いいたします。

**Comment by gazf** [comment]
ご返答ありがとうございました。
個人的にはcontactに反応できれば実装の幅が広がるのかなと思います。
ご検討頂けたら嬉しいです。

**Comment by kazuki-ma** [comment]
ありがとうございます。

頂いた意見、社内で共有させて頂きます。<(_ _)>
