### ISSUE TITLE
displayText postback property for Rich Menu

### ISSUE THREAD

**Issue by kenakamu** [line/line-platform-feedback#68]
# Information to include

- I created a RichMenu with Postback Action by specifying displayText field.
- I, then, retrieve the created RichMenu and see the data, where displayText is missing.

Question: Does RichMenu supports displayText for Postback?

**Comment by synk** [comment]
Thank you for the reporting. I believe now you can find `displayText` in the response JSON of RichMenu API.

**Comment by kenakamu** [comment]
Sorry for delay. I confirmed that it works as expected now :)
