### ISSUE TITLE
Users cannot send some stickers after the bot joins the group

### ISSUE THREAD

**Issue by sura1997** [line/line-platform-feedback#7]
I just have a simple echo bot almost identical to the example in flask-echo (python sdk). 

The bot works fine. I can see requests with different types: text, image, sticker, and video; as it logs details of the requests. Bot can echo back when the request is a text. That's all fine. 

The only problem is there are certain sets of stickers that will fail to send into the group no matter what. At least I know the "Cherry Coco" and "Daily Life" stickers will always fail to send by any users to the group chat. It fails immediately with the icon on the right to allow us to click and retry sending it again, but that will fail too. There was no request sending to the bot server through the webhook (no log of such request). It must be something on the LINE servers to prevent people sending certain set of stickers to the group chat when there is a bot in it. The same problem with a one-on-one chat to the bot too.

Is this a known issue? I would imagine that users would be very annoyed when they are not allowed to send certain stickers that want to use.

**Comment by sura1997** [comment]
Actually, this is not an issue created by the bot. Somehow we can no longer use those stickers for some other reasons. It's nothing to do with the bot.

**Comment by GuitarSucks** [comment]
@sura1997 
Seems like the problem is the sticker itself. You can try to check the expired date of the stamp or try   to re-download it. 
Unfortunately I can't help that much on sticker related problem. If you still have issue please raise the problem at [Problem Report Form](https://contact-cc.line.me/en/)
