### ISSUE TITLE
Is it possible to use the Messaging API in order to control the 1: 1 chat feature supported by LINE @ App? 

### ISSUE THREAD

**Issue by kimjinyam** [line/line-platform-feedback#71]
I would like to switch to LINE@App 1-on-1 chat mode, only when the customer requests (input keyword or enter Event in RichMenu or Button Template).
Because 1: 1 chat mode does not respond automatically.
Can this be implemented with the Messaging API?

![screen shot 2018-02-20 at 4 02 27 pm](https://user-images.githubusercontent.com/22905074/36412401-627b2e6e-165d-11e8-9fa0-77236d677ca4.png)

Attach a picture to help you understand the question.

ps.
LINE @ Enable Messaging API Settings in App Manager

Enabling the API is a permanent action and you will not be able to use the features listed below.
• 1-on-1 Chat
• LINE @ App

If I use the Messaging API, will I be unable to work with LINE @ App?

**Comment by GuitarSucks** [comment]
Hi
Currently enabling Messaging API for LINE@ will disable those features.  This is limited to the LINE@ account you enabled. 
So If you have other LINE@ accounts that don't have Messaging API enabled then you are still able to use LINE@ App for those LINE@ accounts.

**Comment by acro5piano** [comment]
@GuitarSucks Just to be clear, is this feature disable in all plans, or paid plan (such as Pro, premium, ...) can implement this?

**Comment by triasrahman** [comment]
Hi @GuitarSucks , How I can disable the messaging API? I need to use 1-on-1 messaging instead of Bot.

**Comment by GuitarSucks** [comment]
@triasrahman 
It's not possible to switch back which was mentioned when you try to activate Messaging API.
You can still contact our CS about it and they will check if its possible.

https://contact.line.me/
Make sure to select LINE@.

**Comment by GuitarSucks** [comment]
Additional information. We are looking into it and might provide solutions in future releases.
