### ISSUE TITLE
The image detail view does not work on Android.

### ISSUE THREAD

**Issue by okihouse** [line/line-platform-feedback#8]
If I Send a `ImageMessage` to client

Some images does not shown on detail view.

![62346243](https://user-images.githubusercontent.com/13760160/27416653-b9235a76-5749-11e7-8514-07abc4341bdb.png)

How can I show you the pictures?

I have a some urls...

This image is not shown.
https://cdn.dnbb.co.kr/u/pr/11399/1498026226056_d9a58009-53d3-4b1c-9416-68c1d3d9cc7e.png

But this image is shown correctly.
https://s3-ap-northeast-1.amazonaws.com/kyaraten-linebot/SunnyDay/1.png

What's different? (not size)

I will wait for your reply, thank you

**Comment by krrrr38** [comment]
@okihouse 
I'm not sure, but it seems the problem is failure image returns `Content-Type: application/octet-stream`. Could you try with proper `Content-Type`?

```sh
> curl -I https://cdn.dnbb.co.kr/u/pr/11399/1498026226056_d9a58009-53d3-4b1c-9416-68c1d3d9cc7e.png
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Content-Length: 1473
Connection: keep-alive
Date: Thu, 22 Jun 2017 03:59:26 GMT
Last-Modified: Wed, 21 Jun 2017 06:23:47 GMT
ETag: "8f54ee0b5852187039f5f828fcba2c16"
Accept-Ranges: bytes
Server: AmazonS3
Age: 4089
X-Cache: Hit from cloudfront
Via: 1.1 b981e96235ccaca6908055e09992c265.cloudfront.net (CloudFront)
X-Amz-Cf-Id: c8UspBvmxQrWqcMGOueUyNEF3HE-bLZpU29SMqJj3aOS6c4StZEp8g==

> curl -I https://s3-ap-northeast-1.amazonaws.com/kyaraten-linebot/SunnyDay/1.png
HTTP/1.1 200 OK
x-amz-id-2: rDw1YCRSfEFMRdvpl4AnzO+Gp0JwfsITJWNLV2vjVNpDnGqK0+zhkMawGRok/YHZP9BOFYGxmPs=
x-amz-request-id: FDAB9D35197D1C89
Date: Thu, 22 Jun 2017 05:07:57 GMT
Last-Modified: Thu, 15 Jun 2017 11:53:49 GMT
ETag: "b601db0da4b0a354dc55cbd544a4a303"
Accept-Ranges: bytes
Content-Type: image/png
Content-Length: 28086
Server: AmazonS3
```

**Comment by KosukeKamiya** [comment]
@okihouse 
The cause is that "cdn.dnbb.co.kr" uses SNI. 
Since LINE Android app doesn't support SNI, it causes this problem.
(There is also a possibility that Content-Type is also one of the reasons but I think SNI is the main reason.)

**Comment by okihouse** [comment]
@krrrr38 Thank you, It works.
