### ISSUE TITLE
Rich menu is not displayed ...why?

### ISSUE THREAD

**Issue by spinninghamster** [line/line-platform-feedback#92]
I created a rich menu with the instructions here:
https://developers.line.me/en/docs/messaging-api/using-rich-menus/#get-rich-menu-list

1. I created the structure and got an "OK" response.
2. I uploaded the menu image and got an "OK" response.
3. I was able to list and see the rich menu I created with "_/richmenu/list_"

Yet, when opening the bot, I don't see the rich menu displayed.

Is there anything else needed to do to "activate" the rich menu?

Any hints are greatly appreciated. I read the FAQ several times over the past hours and can't figure out what else I need to do. I want the same rich menu displayed to **all** users.

**Comment by kazuki-ma** [comment]
Maybe you need link richMenu to the user.

* https://developers.line.me/en/docs/messaging-api/reference/#link-rich-menu-to-user

**Comment by synk** [comment]
let me close this issue. Please feel free to reopen if you think it isn't solved yet.
