### ISSUE TITLE
.zip, .exe can not set on action object with uri type, but .7z, .tar, .gz, .rar is OK

### ISSUE THREAD

**Issue by PeacePan** [line/line-platform-feedback#97]
Hi, there:

I using the messaging API to send template for download compression file

when the extension of file url is .zip or .exe
ex: 
http://my.domain.com/download/file.zip
http://my.domain.com/download/file.exe

The response of API will return

400 Bad Request [Invalid url]

but .7z, .rar, .tar, .gz is OK

-----------------------------
My solution now

if extension is .zip, .exe, using the url shortener to generate a new url

Why LINE blocks .zip, .exe but does not block other compression extensions

**Comment by synk** [comment]
@PeacePan 
Thank you for your report.
You can not specify such compressed file.  Other compressed file types will be blocked as well in the future.
