### ISSUE TITLE
Any sample how to access camera and mic from LIFF?

### ISSUE THREAD

**Issue by kenakamu** [line/line-platform-feedback#98]
Hi team,

I tried LIFF to see if I can access camera/mic to use WebRTC. However it doesn't give me anything (nor error) when I run navigator.mediaDevices.getUserMedia({ video: true, audio: false }) which works perfect in Safari.

In the [document](https://developers.line.me/en/docs/liff/overview/), you mentioned that we can access to camera and microphone though.

**Comment by tori3** [comment]
Hi @kenakamu.

In LIFF Webiew, Browser's API such as getUserMedia depends on specification of [WKWebview](https://developer.apple.com/documentation/webkit/wkwebview)
As you know, `WebRTC` is supported from iOS 11 in safari, but it is not supported in WKWebview.

http://www.openradar.me/33571214

As with WebRTC, stream data etc can not be handled, but in WKWebview you should be able to access camera using [HTML Media Capture](https://w3c.github.io/html-media-capture/)

https://caniuse.com/#search=HTML%20Media%20Capture

Thanks.
