### ISSUE TITLE
 A camera starts in Anrdoid from LIFF.

### ISSUE THREAD

**Issue by ta-asano** [line/line-platform-feedback#99]
Hi Line Team,

I use LIFF.
When I choose a file among a screen of LIFF, I photograph it with a camera and want to choose it.

I succeed in iOS.
A camera does not start in Android. (a file choice screen is displayed)

I start a camera in Android and want to choose it after photography.

I need your help.

`<input type="file" accept="image/*" capture="camera">`

![liff_android](https://user-images.githubusercontent.com/40486483/41765656-aa68dc70-763f-11e8-89d6-97c9fae92987.png)

**Comment by tori3** [comment]
Hi @ta-asano.

In LIFF webview of Android, capture = "camera" is not supported.
We are considering offering functions that use camera.

Thanks.

**Comment by ta-asano** [comment]
Thank you for your help.

**Comment by jeffjen** [comment]
Please support this feature as this directly affects user experience.

**Comment by zensesage** [comment]
Please support this feature, this is most affects user experience.

**Comment by michliu** [comment]
Please support this feature
